### ISSUE TITLE
flatpak 翻譯並到上游發 Pull Request

### ISSUE THREAD

**Issue by zerng07** [l10n-tw/l10n-tw-translationproject#1]
目前 flatpak 已越來越成熟，待有經驗且有空遐的朋友貢獻翻譯。
翻譯者必須同意本專案的要求：

> 翻譯貢獻者將永不行使其著作權：永不禁止他人複製其翻譯，亦永不尋求任何形式之賠償。任何人隨時皆能自由使用、修改、與散布這些翻譯。

步驟：
一、利用 https://github.com/l10n-tw/flatpak 與 github 版控進行翻譯，並到本 issue 下方認領翻譯
二、翻譯完成後到 https://github.com/flatpak/flatpak/pulls 上游發 Pull Request
三、翻譯術語請遵循 GNOME 慣例，例如軟體管理領域下之 package 為軟體包、extension 為擴充套件、repo 為軟體庫、addon 為附加元件……等，最後成果會由 zerng07 校對

**Comment by s8321414** [comment]
我應該可以試著接手看看XD

**Comment by zerng07** [comment]
本次翻譯工作有來自 l10n-tw 團隊的小獎勵 100USD，資金由無私的網友提供。
https://www.bountysource.com/issues/64274935-flatpak-pull-request

如果有網友想要多支持這樣的獎勵專案，請透過 Bountysource Salt 定期定額贊助 l10n-tw 團隊，感謝！
https://salt.bountysource.com/teams/l10n-tw

**Comment by zerng07** [comment]
已由 @s8321414 翻譯，@zerng07 校對。

Commit 為
https://github.com/l10n-tw/flatpak/commit/c62468efd9d65e4704d0c605b26ebd7a0ac37c57

待上游接受 PR 後關閉本 issue 並發放 bountysource 獎勵。

**Comment by zerng07** [comment]
上游已收。
