### ISSUE TITLE
darktable 翻譯並到上游發 Pull Request

### ISSUE THREAD

**Issue by zerng07** [l10n-tw/l10n-tw-translationproject#2]
darktable 已經存在許久，是攝影常用的 Raw 檔顯色器自由軟體，待有經驗且有空遐的朋友貢獻翻譯。
翻譯者必須同意本專案的要求：

> 翻譯貢獻者將永不行使其著作權：永不禁止他人複製其翻譯，亦永不尋求任何形式之賠償。任何人隨時皆能自由使用、修改、與散布這些翻譯。

步驟：
一、利用 https://github.com/l10n-tw/darktable 與 github 版控進行翻譯，並到本 issue 下方認領翻譯
二、翻譯完成且經過校對後，到 https://github.com/darktable-org/darktable 上游發 Pull Request
三、翻譯術語請遵循 GNOME 慣例，最後成果會由 zerng07 校對

若翻譯期間需要參考既有之顯色器軟體介紹中文書籍（如專有軟體 Lightroom），可向 zerng07 聯絡，願給予書籍贊助。

**Comment by MGdesigner** [comment]
請問是翻譯專案裡面的PO檔嗎？

**Comment by duidae** [comment]
請問我想認領  在這報名嗎？  (有BSD manual翻譯相關經驗)  謝謝！

**Comment by reiscigit** [comment]
想認領+1（開源新手，第一次使用PO檔翻譯）

**Comment by zerng07** [comment]
最近有些忙，我稍晚回覆。

**Comment by zerng07** [comment]
@MGdesigner 是的。要翻譯的是 https://github.com/l10n-tw/darktable/tree/master/po 下的 zh_TW.po 檔。
@duidae 你好！想請問先前有翻譯過 po 檔嗎？以及之前有使用過 raw 檔相關軟體的經驗嗎（沒有亦可，只是本人好奇問問）？
@reiscigit  你好！由於 daktable 是個成熟且龐大的自由軟體，所以如果是開源新手，在初次翻譯軟體與處理 po 檔時，過程或許會遇到些許問題，此時需要熱誠不斷請教與克服。我本人願意擔任翻譯指導者。在這樣的狀況下，我想請問你仍願意認領翻譯嗎？

自由與開源軟體專案精神多推崇能人主義 (meritocracy)，因此若有眾人皆願意認領時，會偏好優先指派給有經驗者。當指派者盡其能力完成所能翻譯的部分後，即同步上傳，讓後續其他人繼續接手、或校對，甚至改善（根據 release early, release often 的精神互相協調工作，減少重複翻譯的勞力作業）。

若有在此 issue 下同意認領的第二、第三貢獻者，我會另外根據貢獻程度比例發予獎金（本次 l10n-tw 翻譯活動以外的獎金，由本人提供）。

**Comment by duidae** [comment]
@zerng07 您好，有的我有用poeditor編輯po檔的經驗，但raw檔比較少用，我本身是作image processing相關的open source software開發

**Comment by reiscigit** [comment]
@zerng07 您好，我願意認領，聽候工作分配。

**Comment by ghost** [comment]
翻譯已經完成。請見 https://github.com/jouston/darktable/blob/master/po/zh_TW.po

**Comment by zerng07** [comment]
@duidae 由於您有經驗，且同意本專案翻譯要求，這項翻譯就先指派給您。請先以自主翻譯優先；但如果有需要，您也可以「參考」既有之簡體翻譯加速流程，請務必以自己的語言與想法再修改、校對過。

在您盡可能翻譯完可以處理的部分後，便上傳翻譯並在此回覆通知一下。翻譯格式請依照目前 GNOME 慣例：

參見自由軟體中文化指引
https://docs.google.com/document/d/1Zs4CS_ZjN-imnImq4aEsiVYih8zkIkVZTSQim13_kYg/edit#heading=h.9k6c1n8885ox

或是摘要版
https://hackmd.io/Ma7R5RfbQvW5ysrd2PlTPg?view

@reiscigit 好的，就請您先等候 duidae 作業，以免重複進行翻譯反覆勞力。我們再看接下來能幫忙哪些部分。

@jouston 您好，在此感謝您將簡體版轉繁並翻譯。不過，由於您先前沒有留言表達參與意願，亦無表明同意本專案翻譯要求，而且並未採用先前我回覆給 MGdesigner 時的檔案進行翻譯，因此無法給予您任何獎金，盼請諒解。
> @MGdesigner 是的。要翻譯的是 https://github.com/l10n-tw/darktable/tree/master/po 下的 zh_TW.po 檔。

**Comment by duidae** [comment]
@zerng07 哇感謝您！！好的我會開始進行翻譯！想請問有時間限制嗎？

**Comment by zerng07** [comment]
> @zerng07 哇感謝您！！好的我會開始進行翻譯！想請問有時間限制嗎？

時間流程預計如下：
如果能在兩個月內完成初步翻譯會最好。
接著一個月再看初步翻譯完成後缺的部分有沒有其他人能補，以及校讀作業（看有無缺漏字、錯字、錯標點等）。
最後由我再校對。
希望能在 3-4 個月內完成。

我前幾日已將 l10n-tw 下的 darktable 與上游同步，並建立對應當下版本的 po 檔。請以這個版本為基礎作翻譯。您也可以利用這個版本自行編譯、建置、測試程式與驗證翻譯成果。
https://github.com/l10n-tw/darktable

翻譯過程也可參考市面書籍用語，例如專有軟體 Lightroom 之類的攝影書。

**Comment by duidae** [comment]
@zerng07 好的瞭解，謝謝您！

**Comment by ghost** [comment]
@zerng07 本人為前任i18n zh_TW coordinator，已於週五於Bounty Source認領該翻譯並開始作業。亦即已同意本專案翻譯要求。若必須以github溝通認領為準來認領並發給獎金。本人並無意見，但是期待下次發包專案時應說明該規則。

本次po共1618條msg需翻譯。目前已經大部分完成並且花了大量時間翻閱lightroom, photoshop以及參考原gnome用語翻譯。並不是單純簡轉繁，您似乎並未認真打開該PO檢視。可否考慮基於我這個版本合併更新之後交由 @reiscigit 翻譯呢？避免重複浪費時間。

**Comment by zerng07** [comment]
Bountysource 上是直接引用本 issue，「步驟」已明確記載認領步驟。

我確實礙於時間有限只稍微看過翻譯，查看過 po 檔標頭、比對 po 檔條目數是否更新至最新狀態、比對部分簡體條目、檢視標點與空格是否遵循本 issue 所指之「GNOME」慣例等。

若您願意，您的翻譯給 duidae 參考利用，我認為並無不可。

**Comment by zerng07** [comment]
@duidae 嗨，不知現在翻譯狀況為何？目前有什麼進展，或是有遇到什麼困難的地方嗎？有任何疑問都歡迎提出，謝謝！

**Comment by duidae** [comment]
hi 您好，目前已經快ok了，預計下週二前可以完成！謝謝您！

**Comment by duidae** [comment]
@zerng07 您好，目前已完成並pull request上去了  PR: https://github.com/l10n-tw/darktable/pull/1
再麻煩您看一下，若有任何需要修改的地方請不吝提出~~謝謝您！

**Comment by zerng07** [comment]
@duidae 非常感謝您！我這幾天會粗略評估，如果沒有太大問題就會發放獎金。
之後我會再花時間校對、更新。
感謝🙏！

**Comment by duidae** [comment]
好的謝謝您！

**Comment by zerng07** [comment]
@duidae 已確認，絕大多數 OK。
少部分需要再修改，例如 GNOME 翻譯格式偏好中英之間補入空格，這部分我再修正即可。

請前往 https://www.bountysource.com/issues/64499542-darktable-pull-request 以 github 帳號登入，選擇 Solve Issue 並 Claim Bounty。

**Comment by duidae** [comment]
@zerng07 歐歐好的太好了～！已填solve issue，再麻煩您謝謝！！新年快樂！

**Comment by zerng07** [comment]
請再 Claim Bounty，謝謝

**Comment by duidae** [comment]
已claim，謝謝您！

**Comment by duidae** [comment]
@zerng07 非常感謝您給我機會來翻譯！這次翻譯學到很多，剛好最近又在開發影像editing的功能，能又認識一個open source的影像軟體真是太好了！收穫非常豐富，希望下次還有機會能一起合作，再次謝謝您！
