### ISSUE TITLE
網友回報匯集一

### ISSUE THREAD

**Issue by zerng07** [l10n-tw/l10n-tw-translationproject#3]
1.  libc-2.29.9000.zh_TW.po，發現有空白翻譯
#: timezone/zic.c:1505
msgid "leap second precedes Epoch"
msgstr ""

#: timezone/zic.c:2107
#, c-format
msgid "%%z UT offset magnitude exceeds 99:59:59"
msgstr ""

#: timezone/zic.c:2631
msgid "two rules for same instant"
msgstr ""

2. 然後剛才在 coreutils-8.30.79.zh_TW.po 看到這段
 msgid "IFree"
-msgstr "I可用"
+msgstr "可用(I)"
 
 msgid "IUse%"
-msgstr "I已用%"
+msgstr "已用(I)%"
 
 msgid "IUsed"
+msgstr "已用(I)"
不確定這樣加大欄位寬度好不好，然後感覺「可用(I)」也沒有比「I可用」傳達更多資訊，只能說原文只寫一個 I 真的很不清楚。

3. coreutils 這種空格應該不要消掉？
msgstr ""
 "\n"
-"請注意，-d 和 -t 選項可接受不同的時間/日期格式。\n"
+"請注意，-d 和-t 選項可接受不同的時間/日期格式。\n"

另外 regular file 的翻譯好像有很多種，coreutils 似乎原本是寫「普通檔案」，最新的翻譯檔出現「一般檔案」，然後 bash 裡有「常規檔案」。

 "\n"
-"SET 是以字串方式指定。大部份字元都會直接處理。要解譯的序列包括：\n"
+"SET 是一組字串，一般都可按照字面含義理解。解析序列如下：\n"
 "\n"
-"  \\NNN            八進位數字 NNN (1 至 3 個位)所代表的字元\n"
+"  \\NNN\t八進位值為NNN 的字元(1 至3 個數位)\n"
似乎又有空格被消掉

後面還有一串這個，感覺括號裡的東西保留起來會比較容易看？
-"  \\a              響聲 (BEL)\n"
-"  \\b              倒退字元 (backspace)\n"
-"  \\f              換頁字元 (form feed)\n"
-"  \\n              換行字元 (new line)\n"
-"  \\r              復位字元 (return)\n"
-"  \\t              水平定位字元 (tab)\n"
+"  \\a\t\t終端鳴響\n"
+"  \\b\t\t退格\n"
+"  \\f\t\t換頁\n"
+"  \\n\t\t換行\n"
+"  \\r\t\tEnter\n"
+"  \\t\t\t水平製表符\n"

-"不加選項的話，程式會產生三欄內容。第一欄的內容只在 <檔案1> 出現，\n"
-"第二欄的只在 <檔案2> 出現，第三欄的則同時在兩個檔案內出現。\n"
+"如果不附加選項，程式會產生三列輸出。第一列包含 檔案1 特有的行，第二列包含 檔"
+"案2 特有的行，而第三列包含兩個檔案共有的行。\n"

column 是「欄」不是「列」吧，然後用空白分隔有比用 <> 分隔好嗎……
另外一個問題是，上面可以看到有不少原文裡是空白的地方被翻譯者替換成 \t，感覺似乎不太對？

這個……我個人是希望不要把參考用的 <> 拿掉啦，然後「出紙頁頁標」、「新行」、「報頭」這些呢，還有出現半型標點。

 "  -e[字元[寬度]], --expand-tabs[=字元[寬度]]\n"
-"                    將輸入資料中的 <字元> (預設為 TAB) 轉換為指定 <寬度> 的\n"
-"                    空格數目 (預設為 8)\n"
-"  -F, -f, --form-feed\n"
-"                    使用 form feed 而不是 newline 字元來分頁 (使用此選項\n"
-"                    時只會印出三行標頭，否則會印出五行標頭再加註腳)\n"
+"\t\t\t擴充輸入的字元(製表符) 到製表符寬度(8)\n"
+"  -F, -f, --form-feed\t使用出紙頁頁標代替新行作為頁面間的分隔符\n"
+"\t\t\t(使用-F 選項時報頭為3 行,不使用時為5 行)\n"

-"  -a, --across      印出內容時會先橫跨所有欄位 (橫向列印)，並非印完一欄才\n"
-"                    跳至第二欄繼續列印；此選項需要配合 -欄數 使用\n"
+"  -a, --across\t\t設定每列從上到下輸出，配合\"-列數\"選項一起使用\n"

中文不應該用 " 吧，然後新的翻譯少掉很多資訊，重點沒講出來，然後「欄」和「列」的問題又出現了。

-"                    使用 ^ 符號 (^G) 或反斜號加八進位數字顯示無法列印的字元\n"
-"  -d, --double-space\n"
-"                    隔行顯示結果\n"
+"\t\t\t使用頭標(^G)和八進位反斜線標記\n"
+"  -d, --double-space\t加倍輸出空白區域\n"

「頭標」有比「^ 符號」好嗎？「加倍輸出」感覺沒有講出每行用兩個換行字元來分隔的本意。
訊息先傳到這裡，感覺我可能也在這個對話框裡洗了太多訊息，雖然我只看了 coreutils 的 po 檔不到 10%，但感覺這個翻譯檔應該要有其他人看過、修改過，以免發生像是 glibc 2.30 那樣的狀況。

4. bison 這個問題看起來還在
msgid "Terminals unused in grammar"
msgstr "終端機在文法中未使用"

那個 terminal 不是終端機，而是文法檔中取代到最後無法再取代的符號。
https://en.wikipedia.org/wiki/Terminal_and_nonterminal_symbols
看起來翻譯檔裡大部分是用「終結語詞」

5. 這個我有記下來，但不太記得是為什麼了。
msgid "$default"
msgstr "$預設"
印象中 $default 好像是檔案中的特殊符號。

6. 再來 gcc，先看哨兵系列
msgid "missing sentinel in function call"
msgstr "函式呼叫中缺少哨兵"

msgid "not enough variable arguments to fit a sentinel"
msgstr "變數引數太少，不足以填滿一個哨兵"

msgid "traditional C rejects the unary plus operator"
msgstr "傳統 C 不接受單位元 + 運算子"

這裡寫「一元運算子」http://terms.naer.edu.tw/detail/1288222/

7. dconf-editor 這個 break 是否該叫「中斷」？
msgid "Don’t forget that some options may break applications, so be careful."
msgstr "別忘了一些選項可能會中斷應用程式，所以要小心。"

8. 這個是 bash
msgid ". filename [arguments]"
msgstr "。檔名 [引數]"
開頭的 . 是指令名稱不能翻譯呀……（就是 . ~/.bashrc 這種指令的第一個字）

msgid ""
"kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l "
"[sigspec]"
msgstr ""
"kill [-s 訊號規格 | -n 訊號編號 | - 訊號規格] 行程識別號 | 工作規格 … 或 "
"kill -l [訊號規格]"

然後這種不知道有沒有共通的處理方法，注意 -sigspec 那項的中文翻譯在 - 後面多加了一個空格，但畢竟這是在解釋指令用法，實際使用指令時 - 後面是不能有那個空格的。

msgid ""
"bind [-lpsvPSVX] [-m keymap] [-f filename] [-q name] [-u name] [-r keyseq] [-"
"x keyseq:shell-command] [keyseq:readline-function or readline-command]"
msgstr ""
"bind [-lpvsPSVX] [-m 鍵對映] [-f 檔名] [-q 名稱] [-u 名稱] [-r 鍵序列] [-x 鍵"
"序列:shell- 命令] [鍵序列:readline- 函數 或 readline- 命令]"

不確定為什麼「shell- 命令」會有個空格在那裡。

9.
$ help eval
eval: eval [引數 …]
    將引數做為 shell 命令執行。
    
    將 ARGs 合成一個字串，用結果做為 shell 的輸入，
    並且執行得到的命令。
    
    退出狀態：
    以命令的狀態退出，或者在命令為空的情況下回傳成功。

 注意原文的「arg」已經在標題被翻譯成「引數」，但下面卻還是寫「ARGs」。

10.
printf: printf [-v var] 格式 [引數]
    在 FORMAT 的控制下格式化並印出 ARGUMENTS 引數。
    
    選項：
      -v var    將輸出指派給 shell 變數 VAR 而不顯示在標準輸出上
    
    FORMAT 是包含三種物件的字串：簡單地被複製到標準輸出的普通字元；
    被變換之後複製到標準輸入的逸出字元；以及每個都會影響到下個引數的印出格式化規格。
    
    在 printf(1) 中描述的標準控制規格之外，printf 解析：
    
      %b        擴充套件對應引數中的反斜線逸出序列
      %q        以可做為 shell 輸入的格式引用引數
      %(fmt)T   以 FMT 為提供 strftime(3) 的格式輸出日期與時間字串    
    退出狀態：
    回傳成功，除非使用了無效的選項或者發生寫入或指派錯誤。

「printf 解析：」下面那行多了一個「、」。
然後跟樓上的 eval 有一樣的問題是，format 和 arguments 在標題已經被換成中文，但內文卻還是寫 FORMAT 和 ARGUMENTS。
另外就是還有排版歪掉的問題。

**Comment by pan93412** [comment]
> 這個是 bash
> msgid ". filename [arguments]"
> msgstr "。檔名 [引數]"
> 開頭的 . 是指令名稱不能翻譯呀……（就是 . ~/.bashrc 這種指令的第一個字）

早就解決了……

**Comment by pan93412** [comment]
> 另外一個問題是，上面可以看到有不少原文裡是空白的地方被翻譯者替換成 \t，感覺似乎不太對？

直接講，我直接拿簡體翻譯轉換，但憑一人之力一則一則審閱十分困難。簡體中文早期翻譯的排版指南是：

  - `中English 中`：中英補空只需補右邊。
  - ` ` > `\t`：用 Tab 代替空白

看得出來跟正體中文的排版指南差很多。不過例如「簡體翻譯 `\t` 所代表的空白寬度不定」、「沒有適合用來解決中英補空問題的正規表示式」等問題難以解決，必須手動審閱。除此之外，還有一些很難取代的中國用法：例如 `所有者組` `使用者組`。

我已盡力[審閱](https://github.com/l10n-tw/coreutils-tw/issues/1)部份翻譯，但難免有漏網之魚。非常感謝回報！

**Comment by pan93412** [comment]
# 網友回報
整理了一下。

## libc
### libc-2.29.9000.zh_TW.po，發現有空白翻譯 [部份解決]
```gettext
#: timezone/zic.c:1505
msgid "leap second precedes Epoch"
msgstr ""
#: timezone/zic.c:2107
#, c-format
msgid "%%z UT offset magnitude exceeds 99:59:59"
msgstr ""

#: timezone/zic.c:2631
msgid "two rules for same instant"
msgstr ""
```

## coreutils
### 剛才在 coreutils-8.30.79.zh_TW.po 看到這段 [已解決]
```diff
msgid "IFree"
-msgstr "I可用"
+msgstr "可用(I)"
msgid "IUse%"
-msgstr "I已用%"
+msgstr "已用(I)%"

msgid "IUsed"
+msgstr "已用(I)"
```

不確定這樣加大欄位寬度好不好，然後感覺「可用(I)」也沒有比「I可用」傳達更多資訊，只能說原文只寫一個 I 真的很不清楚。

### coreutils 這種空格應該不要消掉？[已解決]
```diff
msgstr ""
"\n"
-"請注意，-d 和 -t 選項可接受不同的時間/日期格式。\n"
+"請注意，-d 和-t 選項可接受不同的時間/日期格式。\n"
```

### 另外 regular file 的翻譯好像有很多種 [已解決]
coreutils 似乎原本是寫「普通檔案」，最新的翻譯檔出現「一般檔案」，然後 bash 裡有「常規檔案」。

### 似乎又有空格被消掉 [已解決]
```diff
"\n"
-"SET 是以字串方式指定。大部份字元都會直接處理。要解譯的序列包括：\n"
+"SET 是一組字串，一般都可按照字面含義理解。解析序列如下：\n"
"\n"
-" \NNN 八進位數字 NNN (1 至 3 個位)所代表的字元\n"
+" \NNN\t八進位值為NNN 的字元(1 至3 個數位)\n"
```

### 感覺括號裡的東西保留起來會比較容易看？[已解決]
```diff
-" \a 響聲 (BEL)\n"
-" \b 倒退字元 (backspace)\n"
-" \f 換頁字元 (form feed)\n"
-" \n 換行字元 (new line)\n"
-" \r 復位字元 (return)\n"
-" \t 水平定位字元 (tab)\n"
+" \a\t\t終端鳴響\n"
+" \b\t\t退格\n"
+" \f\t\t換頁\n"
+" \n\t\t換行\n"
+" \r\t\tEnter\n"
+" \t\t\t水平製表符\n"
```

### comm 問題 [已解決]
```diff
-"不加選項的話，程式會產生三欄內容。第一欄的內容只在 <檔案1> 出現，\n"
-"第二欄的只在 <檔案2> 出現，第三欄的則同時在兩個檔案內出現。\n"
+"如果不附加選項，程式會產生三列輸出。第一列包含 檔案1 特有的行，第二列包含 檔"
+"案2 特有的行，而第三列包含兩個檔案共有的行。\n"
```

column 是「欄」不是「列」吧，然後用空白分隔有比用 <> 分隔好嗎……
另外一個問題是，上面可以看到有不少原文裡是空白的地方被翻譯者替換成 \t，感覺似乎不太對？

### pr 問題 [已解決]
```diff
" -e[字元[寬度]], --expand-tabs[=字元[寬度]]\n"
-" 將輸入資料中的 <字元> (預設為 TAB) 轉換為指定 <寬度> 的\n"
-" 空格數目 (預設為 8)\n"
-" -F, -f, --form-feed\n"
-" 使用 form feed 而不是 newline 字元來分頁 (使用此選項\n"
-" 時只會印出三行標頭，否則會印出五行標頭再加註腳)\n"
+"\t\t\t擴充輸入的字元(製表符) 到製表符寬度(8)\n"
+" -F, -f, --form-feed\t使用出紙頁頁標代替新行作為頁面間的分隔符\n"
+"\t\t\t(使用-F 選項時報頭為3 行,不使用時為5 行)\n"
```

這個……我個人是希望不要把參考用的 <> 拿掉啦，然後「出紙頁頁標」、「新行」、「報頭」這些呢，還有出現半型標點。

### pr 問題 [已解決]
```diff
-" -a, --across 印出內容時會先橫跨所有欄位 (橫向列印)，並非印完一欄才\n"
-" 跳至第二欄繼續列印；此選項需要配合 -欄數 使用\n"
+" -a, --across\t\t設定每列從上到下輸出，配合"-列數"選項一起使用\n"
```

中文不應該用 " 吧，然後新的翻譯少掉很多資訊，重點沒講出來，然後「欄」和「列」的問題又出現了。

```diff
-" 使用 ^ 符號 (^G) 或反斜號加八進位數字顯示無法列印的字元\n"
-" -d, --double-space\n"
-" 隔行顯示結果\n"
+"\t\t\t使用頭標(^G)和八進位反斜線標記\n"
+" -d, --double-space\t加倍輸出空白區域\n"
```

「頭標」有比「^ 符號」好嗎？「加倍輸出」感覺沒有講出每行用兩個換行字元來分隔的本意。
訊息先傳到這裡，感覺我可能也在這個對話框裡洗了太多訊息，雖然我只看了 coreutils 的 po 檔不到 10%，但感覺這個翻譯檔應該要有其他人看過、修改過，以免發生像是 glibc 2.30 那樣的狀況。

## bison
### 那個 terminal 不是終端機 [已解決]
bison 這個問題看起來還在

```gettext
msgid "Terminals unused in grammar"
msgstr "終端機在文法中未使用"
```

那個 terminal 不是終端機，而是文法檔中取代到最後無法再取代的符號。
https://en.wikipedia.org/wiki/Terminal_and_nonterminal_symbols
看起來翻譯檔裡大部分是用「終結語詞」

### 印象中 $default 好像是檔案中的特殊符號 [已解決]
這個我有記下來，但不太記得是為什麼了。

```gettext
msgid "$default"
msgstr "$預設"
```

印象中 $default 好像是檔案中的特殊符號。

## gcc
### 哨兵系列 [已解決：改用哨符]
```gettext
msgid "missing sentinel in function call"
msgstr "函式呼叫中缺少哨兵"

msgid "not enough variable arguments to fit a sentinel"
msgstr "變數引數太少，不足以填滿一個哨兵"
```

### 一元運算子 [已解決]
```gettext
msgid "traditional C rejects the unary plus operator"
msgstr "傳統 C 不接受單位元 + 運算子"
```
[這裡](http://terms.naer.edu.tw/detail/1288222/)寫「一元運算子」

## dconf-editor [assigned to @zerng07]
@zerng07 

### 這個 break 是否該叫「中斷」？[未知]
msgid "Don’t forget that some options may break applications, so be careful."
msgstr "別忘了一些選項可能會中斷應用程式，所以要小心。"

## bash
### 開頭的 . 是指令名稱不能翻譯呀 [早已解決]
```gettext
msgid ". filename [arguments]"
msgstr "。檔名 [引數]"
```

開頭的 . 是指令名稱不能翻譯呀……（就是 . ~/.bashrc 這種指令的第一個字）

### 注意 -sigspec 那項的中文翻譯在 - 後面多加了一個空格 [已解決]
```gettext
msgid ""
"kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l "
"[sigspec]"
msgstr ""
"kill [-s 訊號規格 | -n 訊號編號 | - 訊號規格] 行程識別號 | 工作規格 … 或 "
"kill -l [訊號規格]"
```

然後這種不知道有沒有共通的處理方法，注意 -sigspec 那項的中文翻譯在 - 後面多加了一個空格，但畢竟這是在解釋指令用法，實際使用指令時 - 後面是不能有那個空格的。

### 不確定為什麼「shell- 命令」會有個空格在那裡。[已解決]
```gettext
msgid ""
"bind [-lpsvPSVX] [-m keymap] [-f filename] [-q name] [-u name] [-r keyseq] [-"
"x keyseq:shell-command] [keyseq:readline-function or readline-command]"
msgstr ""
"bind [-lpvsPSVX] [-m 鍵對映] [-f 檔名] [-q 名稱] [-u 名稱] [-r 鍵序列] [-x 鍵"
"序列:shell- 命令] [鍵序列:readline- 函數 或 readline- 命令]"
```

不確定為什麼「shell- 命令」會有個空格在那裡。

### eval [已解決]
```
$ help eval
eval: eval [引數 …]
將引數做為 shell 命令執行。

將 ARGs 合成一個字串，用結果做為 shell 的輸入，
並且執行得到的命令。

退出狀態：
以命令的狀態退出，或者在命令為空的情況下回傳成功。
```

注意原文的「arg」已經在標題被翻譯成「引數」，但下面卻還是寫「ARGs」。

### printf [已解決]
```
printf: printf [-v var] 格式 [引數]
在 FORMAT 的控制下格式化並印出 ARGUMENTS 引數。

選項：
  -v var    將輸出指派給 shell 變數 VAR 而不顯示在標準輸出上

FORMAT 是包含三種物件的字串：簡單地被複製到標準輸出的普通字元；
被變換之後複製到標準輸入的逸出字元；以及每個都會影響到下個引數的印出格式化規格。

在 printf(1) 中描述的標準控制規格之外，printf 解析：

  %b        擴充套件對應引數中的反斜線逸出序列
  %q        以可做為 shell 輸入的格式引用引數
  %(fmt)T   以 FMT 為提供 strftime(3) 的格式輸出日期與時間字串    
退出狀態：
回傳成功，除非使用了無效的選項或者發生寫入或指派錯誤。
```

「printf 解析：」下面那行多了一個「、」。
然後跟樓上的 eval 有一樣的問題是，format 和 arguments 在標題已經被換成中文，但內文卻還是寫 FORMAT 和 ARGUMENTS。
另外就是還有排版歪掉的問題。

**Comment by zerng07** [comment]
那個 dconf-editor 的 break，就先暫定「中斷」吧！
如果有想到什麼改善再來改。
