### ISSUE TITLE
darktable 翻譯更新 2023

### ISSUE THREAD

**Issue by zerng07** [l10n-tw/l10n-tw-translationproject#5]
darktable 已經存在許久，是攝影常用的 Raw 檔顯色器自由軟體，需要更新翻譯至最新狀態 (2023年中)。

翻譯者必須同意本專案的要求：
    翻譯貢獻者將永不行使其著作權：永不禁止他人複製其翻譯，亦永不尋求任何形式之賠償。任何人隨時皆能自由使用、修改、與散布這些翻譯。

**Comment by HSUfineprint** [comment]
已於去年開始著手進行繁體中文翻譯，並持續追蹤更新和除錯，目前翻譯更新至最新的 master .POT (截至 2023 七月)。
https://github.com/darktable-org/darktable/pull/14628

**Comment by pan93412** [comment]
那應該是解決了～
